change
t2y/sphinxcontrib-vcs pull request #1
Opened 2017-04-25 09:13 UTC by tatsuro-nishimura

2017-04-25 15:22 UTC, t2y requested changes

2017-04-25 15:22 UTC, t2y commented on sphinxcontrib/vcs.py
> +    return commit.message[0:6] == 'Merged'
I'm not sure how to check "Merged commit", but I think the commit message can be changed other message. Is there proper way?

2017-04-25 15:27 UTC, t2y commented
Why do you want to see only merge commits? How about rebasing several commits before merging them?

2017-04-26 04:56 UTC, tatsuro-nishimura commented
Our clients can see all our commits in html now, but this is not preferable because they can see all our minor changes, so we want to display only merge commits.

2017-04-26 07:09 UTC, t2y commented
> they can see all our minor changes, so we want to display only merge commits.

Does it mean that a merged commit is important change and minor changes are not merged commit? If so, I think it's just a repository operation rule in your team/client. I wonder whether the use case is not common for most developers.

2017-04-26 07:23 UTC, closed without merging

2017-04-27 02:45 UTC, tatsuro-nishimura commented
I closed this request because we have a plan to prepare more sophisticated pull request.